# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop

# 1.18.2
#minecraft_version=1.18.2
#yarn_mappings=1.18.2+build.4
#loader_version=0.14.21
#fabric_version=0.76.0+1.18.2

# 1.19.2
#minecraft_version=1.19.2
#yarn_mappings=1.19.2+build.28
#loader_version=0.16.14
#fabric_version=0.77.0+1.19.2

# minecraft_version=1.20.1
# yarn_mappings=1.20.1+build.10
# loader_version=0.15.11
# fabric_version=0.92.2+1.20.1

# minecraft_version=1.20.4
# yarn_mappings=1.20.4+build.3
# loader_version=0.15.11
# fabric_version=0.97.1+1.20.4

# minecraft_version=1.20.6
# yarn_mappings=1.20.6+build.3
# loader_version=0.15.11
# fabric_version=0.100.0+1.20.6

# 1.21.1
# minecraft_version=1.21.1
# yarn_mappings=1.21.1+build.3
# loader_version=0.16.14
# loom_version=1.10-SNAPSHOT
# fabric_version=0.116.1+1.21.1

# 1.21.9
# minecraft_version=1.21.9
# yarn_mappings=1.21.9+build.1
# loader_version=0.17.2
# loom_version=1.11-SNAPSHOT
# fabric_version=0.134.0+1.21.9

# 1.21.11
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3
loom_version=1.14-SNAPSHOT
fabric_version=0.139.5+1.21.11

# Mod Properties
	mod_version = 1.6
	maven_group = me.isaiah.mods
	archives_base_name = Economy

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	#fabric_version=0.13.1+build.370-1.16
